import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserProvider from "@/app/provider/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-row gap-40">
        <div>
            <h1>this side nav</h1>
        </div>
        <div>
            {children}
        </div>
    </main>
  );
}
